### ISSUE TITLE
Installation via pip on mac

### ISSUE THREAD

**Issue by nucle0tides** [ejmg/tomaty#43]
Installation via pip fails when trying to install the pygobject dependency.

**Comment by nucle0tides** [comment]
running `sudo pip3 install tomaty` worked but i don't....like that for obvious reasons

**Comment by nucle0tides** [comment]
To get it running on Mac it also looks like you will have to install several things via Homebrew. 

```
brew install pygobject3
brew install pygtk
brew install gtk+3
```

**Comment by ejmg** [comment]
dependencies aside, if you are getting sudo related errors, try: `pip3 install --user tomaty` and see if it gives you the same privilege errors?

That part of your issue might be related to your `pyenv` setup. I got those when they weren't expected and had to mess with my `.profile` setup.

**Comment by nucle0tides** [comment]
I might have accidentally installed your package globally with sudo. Press `F` for respect.

**Comment by ejmg** [comment]
`F`

**Comment by ejmg** [comment]
Thanks for documenting, I'll give an update when I next update the README a la #29
