### ISSUE TITLE
total time immediately increments to pomodoro time + break time at the start of a break

### ISSUE THREAD

**Issue by nucle0tides** [ejmg/tomaty#49]
Just went through my first #pomodoro and started my first #pomodoro #break. In an effort to feel good about the effort I've put in so far on this working day, I decided to look at my cumulative effort on the 'stats' tab. I noticed 'Total Time' said 0:30:00 (pomodoro time + break time) instead of 0:25:00 (pomodoro time) at the very start of my break. This seems off.

**Comment by ejmg** [comment]
I think this is honestly a philosophy question. I assumed total time -> time of a pomodoro cycle and thus the pomodoro + the break.

This is up for discussion tho

**Comment by nucle0tides** [comment]
One hasn't spent 30 minutes pomodoro-ing at the start of their five minute break- only at the end of their 5 minute break.

**Comment by ejmg** [comment]
oooooooooooooooooooooooooooooooooooooooooooooooooh i miss read your issue, haven't had my #coffee

**Comment by nucle0tides** [comment]
I made you coffee two hours ago.

**Comment by ejmg** [comment]
Keep talking, i'll be sure to address the issue

![signal-2018-03-30-092434](https://user-images.githubusercontent.com/18218174/38141162-7f7d465c-33fc-11e8-82e0-a4d358c8a3d3.jpeg)

**Comment by ejmg** [comment]
Fixed with 4e5556407f0400e6f12928890b03013e9c393a64
