### ISSUE TITLE
total time incrementing off

### ISSUE THREAD

**Issue by nucle0tides** [ejmg/tomaty#58]
`total time` incremented by only 5 minutes after 25 minutes of pomodoro-ing. Will look into and fix if i get a moment today. 

<img width="271" alt="screen shot 2018-04-02 at 9 25 45 am" src="https://user-images.githubusercontent.com/8785339/38199867-dfd6a748-3657-11e8-8efd-8299dfa362d8.png">

**Comment by nucle0tides** [comment]
update: it increments by 25 mins after a break.

**Comment by ejmg** [comment]
yep, i switched up my counter attributes. i need to rename my stuff so it is more clear what i'm using. fixed with 69abf772300d0903f5e308b299e75a5024f4f4fb
